# Generated by Django 5.0 on 2025-10-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('food', 'FOOD'), ('transport', 'TRANSPORT'), ('shoping', 'SHOPING'), ('other', 'OTHER')], max_length=40)),
            ],
        ),
    ]
